// flow-typed signature: db51389b330001c89317e714141d3d78
// flow-typed version: <<STUB>>/react-scripts_v1.0.7/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-scripts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-scripts' {
  declare module.exports: any;
}
