version: "3"
services:
  frontend:
    build:
      context: ..
      dockerfile: ./dockerfiles/Dockerfile-dev
    volumes:
      - "../frontend:/srv/app"
    ports:
      - "${frontend_port}:3000"
    environment: 
      __DEV__: 1
      CHOKIDAR_USEPOLLING: 1
      REACT_APP_BASE_URL: localhost:${backend_port}
  backend:
    build:
      context: ..
      dockerfile: ./dockerfiles/Dockerfile-dev
    volumes:
      - "../backend:/srv/app" 
    ports:
      - "${backend_port}:3001"
    environment: 
      __DEV__: 1
      CHOKIDAR_USEPOLLING: 1