// flow-typed signature: 3d60f76dd17778240057afdead434fa6
// flow-typed version: <<STUB>>/koa-route_v^3.2.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-route'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-route' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-route/index' {
  declare module.exports: $Exports<'koa-route'>;
}
declare module 'koa-route/index.js' {
  declare module.exports: $Exports<'koa-route'>;
}
