// flow-typed signature: 728470046b1867050ab98d4b82592dd2
// flow-typed version: <<STUB>>/mime_v^1.3.4/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mime' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mime/build/build' {
  declare module.exports: any;
}

declare module 'mime/build/test' {
  declare module.exports: any;
}

declare module 'mime/cli' {
  declare module.exports: any;
}

declare module 'mime/mime' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mime/build/build.js' {
  declare module.exports: $Exports<'mime/build/build'>;
}
declare module 'mime/build/test.js' {
  declare module.exports: $Exports<'mime/build/test'>;
}
declare module 'mime/cli.js' {
  declare module.exports: $Exports<'mime/cli'>;
}
declare module 'mime/mime.js' {
  declare module.exports: $Exports<'mime/mime'>;
}
