// flow-typed signature: 221ba2f5d77e4dcb2ae4f56517da596d
// flow-typed version: <<STUB>>/sockjs_v^0.3.18/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sockjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sockjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sockjs/examples/echo/server' {
  declare module.exports: any;
}

declare module 'sockjs/examples/express-3.x/server' {
  declare module.exports: any;
}

declare module 'sockjs/examples/express/server' {
  declare module.exports: any;
}

declare module 'sockjs/examples/hapi/server' {
  declare module.exports: any;
}

declare module 'sockjs/examples/koa/server' {
  declare module.exports: any;
}

declare module 'sockjs/examples/multiplex/server' {
  declare module.exports: any;
}

declare module 'sockjs/lib/chunking-test' {
  declare module.exports: any;
}

declare module 'sockjs/lib/iframe' {
  declare module.exports: any;
}

declare module 'sockjs/lib/sockjs' {
  declare module.exports: any;
}

declare module 'sockjs/lib/trans-eventsource' {
  declare module.exports: any;
}

declare module 'sockjs/lib/trans-htmlfile' {
  declare module.exports: any;
}

declare module 'sockjs/lib/trans-jsonp' {
  declare module.exports: any;
}

declare module 'sockjs/lib/trans-websocket' {
  declare module.exports: any;
}

declare module 'sockjs/lib/trans-xhr' {
  declare module.exports: any;
}

declare module 'sockjs/lib/transport' {
  declare module.exports: any;
}

declare module 'sockjs/lib/utils' {
  declare module.exports: any;
}

declare module 'sockjs/lib/webjs' {
  declare module.exports: any;
}

declare module 'sockjs/tests/test_server/config' {
  declare module.exports: any;
}

declare module 'sockjs/tests/test_server/server' {
  declare module.exports: any;
}

declare module 'sockjs/tests/test_server/sockjs_app' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sockjs/examples/echo/server.js' {
  declare module.exports: $Exports<'sockjs/examples/echo/server'>;
}
declare module 'sockjs/examples/express-3.x/server.js' {
  declare module.exports: $Exports<'sockjs/examples/express-3.x/server'>;
}
declare module 'sockjs/examples/express/server.js' {
  declare module.exports: $Exports<'sockjs/examples/express/server'>;
}
declare module 'sockjs/examples/hapi/server.js' {
  declare module.exports: $Exports<'sockjs/examples/hapi/server'>;
}
declare module 'sockjs/examples/koa/server.js' {
  declare module.exports: $Exports<'sockjs/examples/koa/server'>;
}
declare module 'sockjs/examples/multiplex/server.js' {
  declare module.exports: $Exports<'sockjs/examples/multiplex/server'>;
}
declare module 'sockjs/index' {
  declare module.exports: $Exports<'sockjs'>;
}
declare module 'sockjs/index.js' {
  declare module.exports: $Exports<'sockjs'>;
}
declare module 'sockjs/lib/chunking-test.js' {
  declare module.exports: $Exports<'sockjs/lib/chunking-test'>;
}
declare module 'sockjs/lib/iframe.js' {
  declare module.exports: $Exports<'sockjs/lib/iframe'>;
}
declare module 'sockjs/lib/sockjs.js' {
  declare module.exports: $Exports<'sockjs/lib/sockjs'>;
}
declare module 'sockjs/lib/trans-eventsource.js' {
  declare module.exports: $Exports<'sockjs/lib/trans-eventsource'>;
}
declare module 'sockjs/lib/trans-htmlfile.js' {
  declare module.exports: $Exports<'sockjs/lib/trans-htmlfile'>;
}
declare module 'sockjs/lib/trans-jsonp.js' {
  declare module.exports: $Exports<'sockjs/lib/trans-jsonp'>;
}
declare module 'sockjs/lib/trans-websocket.js' {
  declare module.exports: $Exports<'sockjs/lib/trans-websocket'>;
}
declare module 'sockjs/lib/trans-xhr.js' {
  declare module.exports: $Exports<'sockjs/lib/trans-xhr'>;
}
declare module 'sockjs/lib/transport.js' {
  declare module.exports: $Exports<'sockjs/lib/transport'>;
}
declare module 'sockjs/lib/utils.js' {
  declare module.exports: $Exports<'sockjs/lib/utils'>;
}
declare module 'sockjs/lib/webjs.js' {
  declare module.exports: $Exports<'sockjs/lib/webjs'>;
}
declare module 'sockjs/tests/test_server/config.js' {
  declare module.exports: $Exports<'sockjs/tests/test_server/config'>;
}
declare module 'sockjs/tests/test_server/server.js' {
  declare module.exports: $Exports<'sockjs/tests/test_server/server'>;
}
declare module 'sockjs/tests/test_server/sockjs_app.js' {
  declare module.exports: $Exports<'sockjs/tests/test_server/sockjs_app'>;
}
